declare var races: string[];
declare var npcManager1: NPCManager;
declare var npcManager2: NPCManager;
declare var loadedRelationships: RelationshipManager;
declare var character1: NPC | undefined;
declare var character2: NPC | undefined;
declare function loadContestants(): void;
declare function updateRelationshipCharacterSelector1(): void;
declare function updateRelationshipCharacterSelector2(): void;
declare function updateRelationshipLabel(): void;
