const NameGenerator = {
	first: function(species: string = "human", gender: string = "female", age: string = "adult"): string {
		var name = "";
		switch (species)
		{
			//#region Aarakocra
			case "aarakocra":
				// define non-gendered aarakocra names
				let aarakocraNames = [
					"Aera",
					"Aial",
					"Aur",
					"Bara",
					"Deekek",
					"Errk",
					"Goost",
					"Heehk",
					"Ikki",
					"Kaaw",
					"Kleeck",
					"Koka",
					"Oorr",
					"Ost",
					"Ouss",
					"Quaf",
					"Quierk",
					"Rok",
					"Salleek",
					"Tuk",
					"Urreek",
					"Zeed"
				];
				// add gender specific names
				if (gender == "male") {
					aarakocraNames.concat([
					]);

				} else
				{
					aarakocraNames.concat([
						"Asharra"
					]);
				}

				name = randomize(aarakocraNames);
				break;
			//#endregion
			//#region Anime
			case "anime":
				if (gender == "male") {
					name = randomize([
						"Akira",
						"Daichi",
						"Goro",
						"Haru",
						"Ichiro",
						"Jiro",
						"Katsuki",
						"Kenji",
						"Kuro",
						"Mirio",
						"Riku",
						"Ryo",
						"Ryuu",
						"Shiro",
						"Tenga"
					]);
				} else {
					name = randomize([
						"Akane",
						"Ayane",
						"Etsuko",
						"Hikari",
						"Izumi",
						"Kasumi",
						"Mei",
						"Mizuki",
						"Natsumi",
						"Ryuko",
						"Shino",
						"Shiori",
						"Takara",
						"Tomoko",
						"Tsuyu",
						"Yuna"
					]);
				}
				break;
			//#endregion
			//#region Bear
			case "bear":
				name = randomize([
						"Bam",
						"Bar",
						"Bash",
						"Bay",
						"Beef",
						"Bob",
						"Bog",
						"Boom",
						"Boo",
						"Bra",
						"Bro",
						"Brak",
						"Brash",
						"Buff"
					]) + randomize([
						"",
						"er",
						"lin",
						"o",
						"s",
						"ski",
						"ster",
						"town",
						"y"
					]);
				break;
			//#endregion
			//#region Bloodfin
			case "bloodfin":
				name = randomize([
					"Bitey",
					"Blood",
					"Bone",
					"Bubble",
					"Hard",
					"Hungry",
					"Leather",
					"Rock",
					"Salt",
					"Stone",
					"Thirsty",
					"Tough"
				]) + randomize([
					"Face",
					"Fin",
					"Jaw",
					"Maw",
					"Scale",
					"Tail",
					"Teeth",
					"Tooth"
				]);
				break;
			//#endregion
			//#region Brokkos
			case "brokkos":
				if (gender == "male") {
					name += randomize([
						"Adalbertu",
						"Alesiu",
						"Ambrosgiu",
						"Andria",
						"Antone",
						"Biasgiu",
						"Baltazaru",
						"Benghjaminu",
						"Bernardu",
						"Boaris",
						"Borisu",
						"Calistu",
						"Carlu",
						"Conradu",
						"Cristofanu",
						"Danelu",
						"Francescu",
						"Gasparu",
						"Giacumu",
						"Ghjaseppu",
						"Larenzu",
						"Lisandru",
						"Martinu",
						"Melchioru",
						"Niculaiu",
						"Petru",
						"Raimondu",
						"Saveriu",
						"Silvestru",
						"Simone",
						"Tumasgiu",
						"Volfgangu"
					]);
				} else {
					name += randomize([
						"Amandina",
						"Angiola",
						"Angioletta",
						"Angiolina",
						"Catalina",
						"Cicilia",
						"Cristina",
						"Edvige",
						"Elodia",
						"Ghjenuveffa",
						"Gnese",
						"Laurenza",
						"Laurenzia",
						"Lisabetta",
						"Lisandra",
						"Lucia",
						"Maria",
						"Martina",
						"Orsula",
						"Rita",
						"Teresia",
						"Saveria",
						"Sofia",
						"Stefania"
					]);
				}
				break;
			//#endregion
			//#region Bugbear
			case "bugbear":
				let nameParts = ["bug", "bar", "ber", "krag", "hak", "kar", "rak", "dos", "gro", "umsch"];
				name = randomize(nameParts) + randomize(nameParts);
				name = name.charAt(0).toUpperCase() + name.slice(1);
				break;
			//#endregion
			//#region Burrowfolk
			case "burrowfolk":
				name = randomize([
					"Shurmie",
					"Burmo",
					"Foro",
					"Rowf",
					"Suko",
					"Rolu",
					"Rofo",
					"Lubo",
					"Bowuf",
					"Wufo",
					"Kulo",
					"Roru"
				]);
				break;
			//#endregion
			//#region Chinese
			case "chinese":
				if (gender == "male") {
					name = randomize([
						"An",
						"Bing",
						"Chen",
						"Chung",
						"Confucius",
						"Cong",
						"Deshi",
						"Dewei",
						"Fo-hai",
						"Fo-hsing",
						"Gan",
						"Gao",
						"Genjo",
						"Ho",
						"Hsin",
						"Huang fu",
						"Hui-chao",
						"HuiK'o",
						"Jiang",
						"Jin",
						"Jing",
						"Jun",
						"Kong",
						"Lao-Tzu",
						"Lee",
						"Lei",
						"Li",
						"Li-Liang",
						"Liang",
						"Liko",
						"Manchu",
						"Ming",
						"Niao-ka",
						"On",
						"Qing-Nan",
						"Quon",
						"Shen",
						"Shing",
						"Sun",
						"Tung",
						"Uang",
						"Wang",
						"Wen",
						"Woo",
						"Wu-pen",
						"Xi-Wang",
						"Xiaoping",
						"Xin",
						"Xing-fu",
						"Yao"
					]);
				} else {
					name = randomize([
						"Ah lam",
						"An",
						"Bao",
						"Chen",
						"Chen-chio",
						"Chen-tao",
						"Chow",
						"Chu hua",
						"Chun",
						"Chyou",
						"Da-Shin",
						"Da-xia",
						"Fai",
						"Fang",
						"Fang hua",
						"Genji",
						"Guanyin",
						"Hua",
						"Hui fang",
						"Jing Wei",
						"Jun",
						"Kimora",
						"Le",
						"Lee",
						"Lei",
						"Li",
						"Li Hua",
						"Li Mei",
						"Li Ming",
						"Lian",
						"Lien",
						"Lin",
						"Ling",
						"Lixue",
						"Mee",
						"Mei",
						"Mingmei",
						"Quan",
						"Shu Fang",
						"Ting",
						"Ushi",
						"Xiang",
						"Xiao-Niao",
						"Xiao-Xing",
						"Xin",
						"Xiu Mei",
						"Yin",
						"Yu",
						"Zan",
						"Zhengqiu",
						"Zhi",
						"Zhijuan",
						"Zi"
					]);
				}
				break;
			//#endregion
			//#region Dragonborn
			case "dragonborn":
				// names listed after 'z' are from Starfinder books. Prior to this are dragonborn names.
				if (gender == "male") {
					name = randomize([
						"Adrex",
						"Arjhan",
						"Azzakh",
						"Balasar",
						"Baradad",
						"Bharash",
						"Bidreked",
						"Dadalan",
						"Dazzazn",
						"Direcris",
						"Donaar",
						"Fax",
						"Gargax",
						"Ghesh",
						"Gorbundus",
						"Greethen",
						"Heskan",
						"Hirrathak",
						"Ildrex",
						"Kaladan",
						"Kerkad",
						"Kiirith",
						"Kriv",
						"Maagog",
						"Medrash",
						"Mehen",
						"Mozikth",
						"Mreksh",
						"Mugrunden",
						"Nadarr",
						"Nithther",
						"Norkruuth",
						"Nykkan",
						"Pandjed",
						"Patrin",
						"Pijjirik",
						"Quarethon",
						"Rathkran",
						"Rhogar",
						"Rivaan",
						"Sethrekar",
						"Shamash",
						"Shedinn",
						"Srorthen",
						"Tarhun",
						"Torinn",
						"Trynnicus",
						"Valorean",
						"Vrondiss",
						"Zedaar",
						"Roslant"
					]);
				} else {
					name = randomize([
						"Akra",
						"Aasathra",
						"Antrara",
						"Aralyx",
						"Arava",
						"Biri",
						"Blendaeth",
						"Burana",
						"Chassath",
						"Daar",
						"Dentratha",
						"Doudra",
						"Driindar",
						"Eggren",
						"Farideh",
						"Findex",
						"Furrele",
						"Gesrethe",
						"Gilkass",
						"Harann",
						"Havilar",
						"Hethress",
						"Hillanot",
						"Jaxi",
						"Jezean",
						"Jheri",
						"Kadana",
						"Kava",
						"Korinn",
						"Megren",
						"Mijira",
						"Mishann",
						"Nala",
						"Nuthra",
						"Perra",
						"Pogranix",
						"Pyxrin",
						"Quespa",
						"Raiann",
						"Rezena",
						"Ruloth",
						"Saphara",
						"Savaran",
						"Sora",
						"Surina",
						"Synthrin",
						"Tatyan",
						"Thava",
						"Uadjit",
						"Vezera",
						"Zykroff",
						"Binata"
					]);
				}
				break;
			//#endregion
			//#region Drow
			case "drow":
				if (gender == "male") {
					name = randomize([
						"Alton",
						"Balok",
						"Baragh",
						"Beidnach",
						"Belaern",
						"Belgos",
						"Bemril",
						"Berg'inyon",
						"Bhintel",
						"Brorn",
						"Bruherd",
						"Caelkoth",
						"Callimar",
						"Ceobarn",
						"Chakos",
						"Chaszmyr",
						"Coranzen",
						"Dantrag",
						"Dhuunyl",
						"Dinin",
						"Dresmorlin",
						"Dro",
						"Duagloth",
						"Durdyn",
						"Elamshin",
						"Elendar",
						"Elkantar",
						"Ellandail",
						"Filraen",
						"Ghaundan",
						"Ghaundar",
						"Guldor",
						"Guldor",
						"Gwylyss",
						"Hadrogh",
						"Hatch'net",
						"Honemmeth",
						"Houndaer",
						"Ildan",
						"Ilmryn",
						"Ilphrin",
						"Imbros",
						"Irennan",
						"Istolil",
						"Istorvir",
						"Iymril",
						"Jaezred",
						"Jalynfein",
						"Jeggred",
						"Jevan",
						"Jhaamdath",
						"Jhaldrym",
						"Jivvin",
						"Jyslin",
						"K'yorl",
						"Kalannar",
						"Kethan",
						"Kluthruel",
						"Kophyn",
						"Krenaste",
						"Krondorl",
						"Kunoris",
						"Kyorlin",
						"Lesaonar",
						"Lirdnolu",
						"Llaulmyn",
						"Malaggar",
						"Micarlin",
						"Minolin",
						"Molvayas",
						"Morennel",
						"Nadal",
						"Nalfein",
						"Narissorin",
						"Narlros",
						"Nilonim",
						"Nimruil",
						"Numrini'th",
						"Nyloth",
						"Nym",
						"Omareth",
						"Orgoloth",
						"Ornaryn",
						"Pharaun",
						"Pharius",
						"Quave",
						"Quendar",
						"Quevven",
						"Raimsael",
						"Ranaghar",
						"Relonor",
						"Riklaunim",
						"Rinnill",
						"Ristel",
						"Ruathym",
						"Ryld",
						"Ryltar",
						"Sabal",
						"Selakiir",
						"Seldszar",
						"Seldszar",
						"Sengo",
						"Solaufein",
						"Sorn",
						"Syrdar",
						"Szordrin",
						"Szordrin",
						"Taldinyon",
						"Tarlyn",
						"Tathlyn",
						"Tazennin",
						"Tebryn",
						"Tolokoph",
						"Torrellan",
						"Trelgath",
						"Tsabrak",
						"Urlryn",
						"Valas",
						"Veldrin",
						"Velkyn",
						"Vhurdaer",
						"Vhurindrar",
						"Vielyn",
						"Vlondril",
						"Vorn",
						"Vuzlyn",
						"Welverin",
						"Xarann",
						"Xundus",
						"Yazston",
						"Yuimmar",
						"Zaknafein",
						"Zeerith",
						"Zyn"
					]);
				} else {
					name = randomize([
						"Ahlysaaria",
						"Akordia",
						"Alaunirra",
						"Alystin",
						"Amalica",
						"Angaste",
						"Anluryn",
						"Ardulace",
						"Aunrae",
						"Balaena",
						"Baltana",
						"Bautha",
						"Belarbreena",
						"Beszrima",
						"Brigantyna",
						"Briza",
						"Brorna",
						"Burryna",
						"Byrtyn",
						"Caya",
						"Cazna",
						"Chadra",
						"Chadzina",
						"Chalithra",
						"Chandara",
						"Chardalyn",
						"Charinida",
						"Charlindra",
						"Chenzira",
						"Chessintra",
						"Dhaunae",
						"Dilynrae",
						"Drada",
						"Drisinil",
						"Eclavdra",
						"Elerra",
						"Elvanshalee",
						"Elvraema",
						"Erakasyne",
						"Ereldra",
						"Faeryl",
						"Felyndiira",
						"Felyndiira",
						"Filfaere",
						"G'eldriia",
						"Gaussra",
						"Ghilanna",
						"Greyanna",
						"Gurina",
						"Haelra",
						"Halisstra",
						"Ilharess",
						"Ilivarrra",
						"Ilmra",
						"Imrae",
						"Jaelryn",
						"Jezzara",
						"Jhaelryna",
						"Jhaelrynna",
						"Jhalass",
						"Jhangara",
						"Jhanniss",
						"Jhulae",
						"Khaless",
						"Kiaran",
						"Laele",
						"Laele",
						"Larynda",
						"LiNeerlay",
						"Lledrith",
						"Llolfaen",
						"Lualyrr",
						"Lythrana",
						"Malindeil",
						"Maya",
						"Menzoberra",
						"Mez'Barris",
						"Micarlin",
						"Miz'ri",
						"Mizzrym",
						"Myrymma",
						"Narcelia",
						"Nathrae",
						"Nedylene",
						"Nendra",
						"Nizana",
						"Nulliira",
						"Olorae",
						"Pellanistra",
						"Phaere",
						"Phyrra",
						"Qilue",
						"Quarra",
						"Quenthel",
						"Rauva",
						"Rilrae",
						"Sabrae",
						"Saradreza",
						"Sassandra",
						"Schezalle",
						"Shimyra",
						"ShriNeerune",
						"Shulvallriel",
						"Shurdriira",
						"Shurdriira",
						"Shurraenil",
						"Shyntlara",
						"SiNafay",
						"Sindyrrith",
						"Solenzara",
						"Ssapriina",
						"T'risstree",
						"Talabrina",
						"Talice",
						"Tallrene",
						"Thalra",
						"Thirza",
						"Thraele",
						"Triel",
						"Ulitree",
						"Ulviirala",
						"Umrae",
						"Urlryn",
						"Urmelena",
						"Vhondryl",
						"Viconia",
						"Vierna",
						"Villyth",
						"Vornalla",
						"Waerva",
						"Wuyondra",
						"Xalyth",
						"Xullrae",
						"Xune",
						"Yasrena",
						"Yvonnel",
						"Z'ress",
						"Zarra",
						"Zebeyana",
						"Zeerith",
						"Zelpassa",
						"Zendalure",
						"Zesstra",
						"Zirachaun",
						"Zilvra"
					]);
				}
				break;
			//#endregion
			//#region Dwarf
			case "dwarf":
				if (gender == "male") {
					name = randomize([
						"Adrik",
						"Alberich",
						"Baern",
						"Barendd",
						"Beloril",
						"Brodain",
						"Brottor",
						"Bruenor",
						"Dain",
						"Dalgal",
						"Darrak",
						"Deldrig",
						"Delg",
						"Duergath",
						"Duravor",
						"Dworic",
						"Eberk",
						"Einkil",
						"Elaim",
						"Erias",
						"Fallond",
						"Fargrim",
						"Flint",
						"Gardain",
						"Gilthur",
						"Gimgen",
						"Gimurt",
						"Gundren",
						"Harbek",
						"Kildrak",
						"Kilvar",
						"Morgran",
						"Morkral",
						"Nalral",
						"Nordak",
						"Nuraval",
						"Oloric",
						"Olunt",
						"Orsik",
						"Oskar",
						"Ragnar",
						"Rangrim",
						"Reirak",
						"Rurik",
						"Taklinn",
						"Thoradin",
						"Thorin",
						"Thradal",
						"Tordek",
						"Traubon",
						"Travok",
						"Ulfgar",
						"Uraim",
						"Veit",
						"Vonbin",
						"Vondal",
						"Whurbin"
					]);
				} else {
					name = randomize([
						"Amarith",
						"Amber",
						"Anbera",
						"Artin",
						"Audhild",
						"Balifra",
						"Barbena",
						"Bardryn",
						"Bolhild",
						"Brumhilda",
						"Dagnal",
						"Dariff",
						"Delre",
						"Diesa",
						"Eldeth",
						"Eridred",
						"Falkrunn",
						"Fallthra",
						"Finellen",
						"Gillydd",
						"Gunnloda",
						"Gurdis",
						"Helgret",
						"Helja",
						"Hilda",
						"Hlin",
						"Ilde",
						"Istrid",
						"Jarana",
						"Kathra",
						"Kilia",
						"Kristryd",
						"Liftrasa",
						"Marastyr",
						"Mardred",
						"Morana",
						"Nalaed",
						"Nora",
						"Nurkara",
						"Oriff",
						"Ovina",
						"Riswynn",
						"Sannl",
						"Therlin",
						"Thodris",
						"Thoretta",
						"Thorina",
						"Torbera",
						"Tordrid",
						"Torgga",
						"Torveda",
						"Urshar",
						"Valida",
						"Vistra",
						"Vonana",
						"Werydd",
						"Whurdred",
						"Yurgunn"
					]);
				}
				break;
			//#endregion
			//#region Elf
			case "elf":
				if (gender == "male") {
					name = randomize([
						"Abadda",
						"Abarat",
						"Adamar",
						"Adorellan",
						"Adran",
						"Adresin",
						"Aduce",
						"Aelar",
						"Aelrindel",
						"Aerendyl",
						"Aermhar",
						"Aesar",
						"Aeson",
						"Afamrail",
						"Agis",
						"Aglanthol",
						"Ainésilver",
						"Aithlin",
						"Ajaar",
						"Akhelbhen",
						"Akkar",
						"Alabyran",
						"Albondiel",
						"Alinar",
						"Allain",
						"Alok",
						"Alosrin",
						"Althidon",
						"Amrynn",
						"Anarallath",
						"Andaerean",
						"Andrathath",
						"Anfalen",
						"Anlyth",
						"Aolis",
						"Aquilan",
						"Araevin",
						"Aramil",
						"Arandron",
						"Arannis",
						"Aravilar",
						"Arbane",
						"Ardreth",
						"Ardryll",
						"Argus",
						"Arkhun",
						"Arkiem",
						"Arl",
						"Arlen",
						"Arun",
						"Ascal",
						"Athtar",
						"Aubric",
						"Aubron",
						"Aulathar",
						"Aulauthar",
						"Aumanas",
						"Aumrauth",
						"Aust",
						"Avourel",
						"Baerdelcoam",
						"Baerithryn",
						"Beiro",
						"Belanor",
						"Beldroth",
						"Bellas",
						"Belstram",
						"Beluar",
						"Berrian",
						"Bhyrindaar",
						"Biafyndar",
						"Bialaer",
						"Braern",
						"Brindarry",
						"Buttorwyr",
						"Cameron",
						"Carric",
						"Chaalmyth",
						"Chathanglas",
						"Cheyrth",
						"Chozzaster",
						"Chylnoth",
						"Cluhurach",
						"Cluym",
						"Cohnal",
						"Conall",
						"Connak",
						"Cornaith",
						"Corym",
						"Cymbiir",
						"Cystenn",
						"Dakath",
						"Dalyor",
						"Dannyd",
						"Daratrine",
						"Darcassan",
						"Darfin",
						"Darthoridan",
						"Deldrach",
						"Delmuth",
						"Delsaran",
						"Dhoelath",
						"Divisav",
						"Drannor",
						"Droth",
						"Druindar",
						"Durlan",
						"Durothil",
						"Dyffros",
						"Earynspieir",
						"Edansyr",
						"Edicûve",
						"Edwyrd",
						"Edyrm",
						"Ehlark",
						"Ehrendil",
						"Eilauver",
						"Elaethan",
						"Elaith",
						"Elandorr",
						"Elanjar",
						"Elashor",
						"Elbauthin",
						"Elbereth",
						"Eldaernth",
						"Eldar",
						"Eldrin",
						"Elénaril",
						"Elenshaer",
						"Elephon",
						"Elhieardacil",
						"Elidyr",
						"Elion",
						"Elkhazel",
						"Ellisar",
						"Elorfindar",
						"Elorshin",
						"Elpaerae",
						"Eltaor",
						"Eltargrim",
						"Emmyth",
						"Enialis",
						"Entrydal",
						"Erdan",
						"Erendriel",
						"Erevan",
						"Erglareo",
						"Eriladar",
						"Erlan",
						"Erlathan",
						"Eroan",
						"Erol",
						"Erolith",
						"Eschallus",
						"Estelar",
						"Ethlando",
						"Ettrian",
						"Euchoé",
						"Evindal",
						"Eyrynnhv",
						"Faahresc",
						"Faelar",
						"Faelyn",
						"Faeranduil",
						"Falael",
						"Faoraar",
						"Felaern",
						"Fenian",
						"Fflar",
						"Fhaornik",
						"Fhociin",
						"Filarion",
						"Filvendor",
						"Filverel",
						"Finufaranell",
						"Flardryn",
						"Flinar",
						"Foxfire",
						"Fylson",
						"Gaeleath",
						"Gaelin",
						"Galaeron",
						"Galan",
						"Galather",
						"Galinndan",
						"Ganamede",
						"Gantar",
						"Garrik",
						"Garynnon",
						"Giilvas",
						"Giullio",
						"Glarald",
						"Glorandal",
						"Goronyyv",
						"Grathgor",
						"Haalaari",
						"Hachaam",
						"Hadarai",
						"Haemir",
						"Haladavar",
						"Halafarin",
						"Halamar",
						"Haldreithen",
						"Halflar",
						"Halgondas",
						"Halpaeril",
						"Halueth",
						"Halueve",
						"Haryk",
						"Hastos",
						"Hatharal",
						"Heian",
						"Hiflanyl",
						"Himo",
						"Hoccar",
						"Horith",
						"Hubyr",
						"Iefyr",
						"Ievos",
						"Ihimbraskar",
						"Ilbryn",
						"Ilimitar",
						"Iliphar",
						"Ilitharath",
						"Illianaro",
						"Illithor",
						"Illitran",
						"Ilphas",
						"Ilrune",
						"Ilthuryn",
						"Ilyndrathyl",
						"Immeral",
						"Inchel",
						"Inialos",
						"Injros",
						"Intevar",
						"Iolas",
						"Iolrath",
						"Itham",
						"Ithraides",
						"Ivellios",
						"Ivlisar",
						"Ivósaar",
						"Ivran",
						"Iymbryl",
						"Iyrandrar",
						"Iyriklaunavan",
						"Jandar",
						"Jannalor",
						"Jaonos",
						"Jassin",
						"Jhaan",
						"Jhaartael",
						"Jhaeros",
						"Jharak",
						"Jharym",
						"Jhuvik",
						"Jonas",
						"Jonik",
						"Jorildyn",
						"Josidiah",
						"Juppar",
						"Kahvoerm",
						"Kalaerede",
						"Katar",
						"Katyr",
						"Keletheryl",
						"Kelvhan",
						"Kendel",
						"Kerym",
						"Keryth",
						"Kesefehon",
						"Khaalindaan",
						"Kharis",
						"Khatar",
						"Khidell",
						"Khiiral",
						"Khilseith",
						"Khuumal",
						"Khyrmn",
						"Khyssoun",
						"Kindroth",
						"Kivessin",
						"Kiyuigh",
						"Klaern",
						"Kolvar",
						"Korrigash",
						"Kroloth",
						"Kuornos",
						"Kuskyn",
						"Kymil",
						"Kyrtaar",
						"Laeroth",
						"Lafarallin",
						"Lamruil",
						"Laosx",
						"Larongar",
						"Larrel",
						"Lashul",
						"Lathai",
						"Lathlaeril",
						"Laucian",
						"Leayonadas",
						"Leojym",
						"Lhombaerth",
						"Lhoris",
						"Lianthorn",
						"Llarm",
						"Llewellenar",
						"Llombaerth",
						"Lorsan",
						"Luirlan",
						"Luthais",
						"Luvon",
						"Lyari",
						"Lyklor",
						"Lysanthir",
						"Maasli",
						"Maendellyn",
						"Maeraddyth",
						"Maeral",
						"Maiele",
						"Malgath",
						"Mardeiym",
						"Marikoth",
						"Marlevaur",
						"Melandrach",
						"Melisander",
						"Merellien",
						"Merith",
						"Methild",
						"Mhaenal",
						"Mi’tilarro",
						"Mihangyl",
						"Miilaethorn",
						"Miirphys",
						"Mindartis",
						"Mirthal",
						"Mlartlar",
						"Mlossae",
						"Molonym",
						"Molostroi",
						"Montagor",
						"Morgan",
						"Morthil",
						"Mothrys",
						"Mourn",
						"Myrddin",
						"Myriil",
						"Myrin",
						"Myronthilar",
						"Mythanthar",
						"Naertho",
						"Naeryndam",
						"Napraeleon",
						"Narbeth",
						"Nardual",
						"Nelaeryn",
						"Neldor",
						"Nesterin",
						"Nevarth",
						"Nhamashal",
						"Nieven",
						"Nindrol",
						"Ninthalor",
						"Nlossae",
						"Nopos",
						"Norlorn",
						"Nremyn",
						"Nuvian",
						"Nyaalsir",
						"Nylian",
						"Nym",
						"Nyvorlas",
						"Oacenth",
						"Oenel",
						"Ohmbryn",
						"Olaurae",
						"Olinsivver",
						"Olithir",
						"Onas",
						"Oncith",
						"Ondabrar",
						"Ondroth",
						"Onvyr",
						"Orist",
						"Orlpar",
						"Orndacil",
						"Ornthalas",
						"Ortauré",
						"Orym",
						"Oslarelar",
						"Otaehryn",
						"Otaerhyn",
						"Othorion",
						"Paelias",
						"Paeral",
						"Paeris",
						"Passilorris",
						"Paulorin",
						"Peren",
						"Phaendar",
						"Pharom",
						"Phraan",
						"Pirphal",
						"Pleufan",
						"Purtham",
						"Pyrder",
						"Pyrravym",
						"Pywaln",
						"Pyxaanthal,",
						"Qildor",
						"Quarion",
						"Quastarte",
						"Quynn",
						"Raeranthur",
						"Raibyr",
						"Ralikanthae",
						"Ralnor",
						"Rathal",
						"Raunaeril",
						"Rauthomyr",
						"Rauvelore",
						"Reluraun",
						"Reluvethel",
						"Rennyn",
						"Reptar",
						"Respen",
						"Rhaac'var",
						"Rhalyf",
						"Rhangyl",
						"Rhenalyrr",
						"Rhespen",
						"Rhistel",
						"Rhothomir",
						"Rhys",
						"Riardon",
						"Rilitar",
						"Riluaneth",
						"Rolen",
						"Rolim",
						"Rotheloe",
						"Rothilion",
						"Ruardh",
						"Ruehar",
						"Ruith",
						"Rumathil",
						"Ruvaen",
						"Ruven",
						"Ruvyn",
						"Rychell",
						"Ryfon",
						"Ryul",
						"Ryvvik,",
						"Sadalymn",
						"Saelethil",
						"Saevel",
						"Sakrattars",
						"Samblar",
						"Sandevv",
						"Seanchai",
						"Seith",
						"Seiveril",
						"Selanlar",
						"Selgauth",
						"Shael",
						"Shammath",
						"Sharian",
						"Sharlario",
						"Shaundyl",
						"Shevarash",
						"Shonassir",
						"Shyrrik",
						"Siirist",
						"Silvyr",
						"Simimar",
						"Sinaht",
						"Skalanis",
						"Sontar",
						"Soveliss",
						"Srindin",
						"Strohm",
						"Sudryl",
						"Sundamar",
						"Sylvar",
						"Symkalr",
						"Sythaeryn",
						"T’karon",
						"Taanyth",
						"Taegen",
						"Taeglyn",
						"Taenaran",
						"Taeral",
						"Taerntym",
						"Taleisin",
						"Tammson",
						"Tamnaeuth",
						"Tamsin",
						"Tanithil",
						"Tannivh",
						"Tannyll",
						"Tanseril",
						"Tanyl",
						"Taranath",
						"Tarathiel",
						"Taredd",
						"Tarosspur",
						"Tarron",
						"Tasar",
						"Tassarion",
						"Tathaln",
						"Tehlmar",
						"Teirist",
						"Tenyajn",
						"Tethir",
						"Thalanil",
						"Thallan",
						"Thamior",
						"Tharivol",
						"Thatoryl",
						"Theren",
						"Thiilthan",
						"Thurdan",
						"Thurruvyn",
						"Tiarshus",
						"Tlannatar",
						"Tolthe",
						"Tordynnar",
						"Toross",
						"Traeliorn",
						"Travaran",
						"Triandal",
						"Triktappic",
						"Tsaer",
						"Tsiilmas",
						"Tyvollus",
						"Ualair",
						"Uevareth",
						"Uldreiyn",
						"Urddusk",
						"Usunaar",
						"Uthorim",
						"Vaalyun",
						"Vaeril",
						"Valmaxian",
						"Vander",
						"Varis",
						"Vartan",
						"Velethuil",
						"Venali",
						"Vesperr",
						"Vesryn",
						"Vesstan",
						"Vhoadan",
						"Vhoorhin",
						"Vhoori",
						"Volodar",
						"Voron",
						"Waernas",
						"Wistari",
						"Wylchyr",
						"Wylym",
						"Wyn",
						"Wyndelleu",
						"Wyqhael",
						"Wyrran",
						"Xalph",
						"Xanotter",
						"Xhalh",
						"Xhalth",
						"Xharlion",
						"Yalathanil",
						"Yeschant",
						"Yhendorn",
						"Ylyndar",
						"Ynloeth",
						"Zabbas",
						"Zaltarish",
						"Zandro",
						"Zaor",
						"Zaos",
						"Zelphar",
						"Zhoron",
						"Zulae"
					]);
				} else {
					name = randomize([
						"Adrie",
						"Aelieyeeva",
						"Aelrue",
						"Aelynthi",
						"Aerilaya",
						"Ahrendaaria",
						"Ahrendue",
						"Ahskahala",
						"Ajhalanda",
						"Alaglossa",
						"Alais",
						"Alauthshaee",
						"Alavara",
						"Alea",
						"Alerathla",
						"Allannia",
						"Allisa",
						"Alloralla",
						"Allynna",
						"Almithara",
						"Aloevan",
						"Althaea",
						"Aluendalee",
						"Alvaerele",
						"Alyndra",
						"Amara",
						"Amaranthae",
						"Amkissra",
						"Amlaruil",
						"Amnestria",
						"Amra",
						"Anaharae",
						"Anarzee",
						"Anastrianna",
						"Andraste",
						"Aneirin",
						"Anhaern",
						"Antinua",
						"Anyllan",
						"Ara",
						"Araushnee",
						"Aravae",
						"Arcaena",
						"Arielimnda",
						"Arlayna",
						"Arnarra",
						"Artin",
						"Ashemmi",
						"Aubaudameira",
						"Auluua",
						"Aurae",
						"Ava",
						"Axilya",
						"Ayaeqlarune",
						"Azariah",
						"Bethrynna",
						"Bhuraelea",
						"Birel",
						"Blythswana",
						"Bonnalurie",
						"Braerindra",
						"Caelynn",
						"Caerthynna",
						"Calarel",
						"Cauladra",
						"Chaenath",
						"Chalsarda",
						"Chandrelle",
						"Chasianna",
						"Chichlandra",
						"Chin’nesstre",
						"Chomylla",
						"Cilivren",
						"Ciyradyl",
						"Claire",
						"Csharynn",
						"Daenalaia",
						"Daratrine",
						"Darshee",
						"Dasyra",
						"Dathlue",
						"Delimbiyra",
						"Delshandra",
						"Deularla",
						"Drusilia",
						"Duilya",
						"Eallyrl",
						"Ecaeris",
						"Edraele",
						"Elanalue",
						"Elanil",
						"Elasha",
						"Eldratha",
						"Elénaril",
						"Eletha",
						"Ellarian",
						"Ellifain",
						"Eloen",
						"Elora",
						"Elvandaruil",
						"Embrae",
						"Emvorele",
						"Enajharas",
						"Enna",
						"Eshenesra",
						"Essaerae",
						"Esta",
						"Ester",
						"Esyae",
						"Faranni",
						"Faunalyn",
						"Felosial",
						"Fhaertala",
						"Fieryat",
						"Filaurel",
						"Filauria",
						"Fildaerae",
						"Fox-at-Twilight",
						"Francessca",
						"Gaelira",
						"Gaerradh",
						"Gaylia",
						"Gemstarzah",
						"Ghilanna",
						"Glynnii",
						"Gweyr",
						"Gwynnestri",
						"Gylledha",
						"Haalija",
						"Hacathra",
						"Halaema",
						"Halama",
						"Halanaestra",
						"Hamalitia",
						"Haramara",
						"Helartha",
						"Hhora",
						"Holone",
						"Huquethae",
						"Hycis",
						"Iahalae",
						"Ialantha",
						"Ielenia",
						"Ikeshia",
						"Ildilyntra",
						"Ilmadia",
						"Ilsevel",
						"Ilyrana",
						"Ilythyrra",
						"Imdalace",
						"Imizael",
						"Immianthe",
						"Imra",
						"Imramarthree",
						"Imryll",
						"Innovindil",
						"Ioelena",
						"Irhaal",
						"Isciira",
						"Isilfarrel",
						"Ithrythra",
						"Itiireae",
						"Itylra",
						"Jastra",
						"Jeardra",
						"Jelenneth",
						"Jhaer",
						"Jhalass",
						"Jhanandra",
						"Jhaumrithe",
						"Jhiilsraa",
						"Kavrala",
						"Kaylessa",
						"Keerla",
						"Keishara",
						"Kethryllia",
						"Keya",
						"Keyleth",
						"Khiipaera",
						"Kileontheal",
						"Kythaela",
						"Laamtora",
						"Laerdya",
						"Laerune",
						"Laurlaethee",
						"Lazziar",
						"Leilatha",
						"Leshanna",
						"Lia",
						"Liluth",
						"Llamryl",
						"Lorelei",
						"Lydi’aleera",
						"Lyraesel",
						"Maaleshiira",
						"Maelyrra",
						"Maeralya",
						"Maith",
						"Makaela",
						"Malruthiia",
						"Mariona",
						"Marissa",
						"Martainn",
						"Meira",
						"Melarue",
						"Merethyl",
						"Merialeth",
						"Meriel",
						"Meriele",
						"Merlara",
						"Mialee",
						"Mistale",
						"Mladris",
						"Mnuvae",
						"Morgwais",
						"Moryggan",
						"Muerlara",
						"Mylaela",
						"Mylaerla",
						"Myriani",
						"Naevys",
						"Naivara",
						"Nakiasha",
						"Nambra",
						"Namyriitha",
						"Nanalethalee",
						"Nanthee",
						"Nanthleene",
						"Naumys",
						"Nlaea",
						"Nuala",
						"Nueleth",
						"Nuovis",
						"Nushala",
						"Nylaathria",
						"Ochyllyss",
						"Oluevaera",
						"Phaerl",
						"Phantyni",
						"Phelorna",
						"Phuingara",
						"Phyrra",
						"Pollae",
						"Puorlaas",
						"Qemba",
						"Quamara",
						"Quelenna",
						"Quillathe",
						"Raejiisa",
						"Raerauntha",
						"Rathiain",
						"Renestrae",
						"Roanmara",
						"Ruavia",
						"Rubrae",
						"Ryllae",
						"Saelihn",
						"Saélihn",
						"Saida",
						"Sakaala",
						"Sariandi",
						"Sariel",
						"Sarya",
						"Schimae",
						"Seirye",
						"Seldanna",
						"Selussa",
						"Séonais",
						"Shadowmoon",
						"Shael",
						"Shalana",
						"Shalantha",
						"Shalendra",
						"Shalheira",
						"Shanairra",
						"Shandalar",
						"Shanyrria",
						"Sharaera",
						"Shava",
						"Sheedra",
						"Sheera",
						"Shi’larra",
						"Shialaevar",
						"Shoulree",
						"Shyael",
						"Shyllisyrr",
						"Silaqui",
						"Sinnafain",
						"Soliania",
						"Soora",
						"Sorsasta",
						"Susklahava",
						"Sylmae",
						"Symrustar",
						"Syndra",
						"Synnorha",
						"Syrune",
						"Syviis",
						"Taenya",
						"Takari",
						"Talaedra",
						"Talanashta",
						"Talila",
						"Talindra",
						"Tamara",
						"Tarasynora",
						"Teharissa",
						"Teryani",
						"Thalaera",
						"Thalanil",
						"Thaola",
						"Thasitalia",
						"Theirastra",
						"Thia",
						"Throleatha",
						"Tiatha",
						"Tira’allara",
						"Tiriara",
						"Tisharu",
						"Tsarra",
						"Tyllaetha,",
						"Ulelesse",
						"Unae",
						"Urmicca",
						"Uschymna",
						"Vadania",
						"Vaervenshalice",
						"Valanthe",
						"Valindra",
						"Vashti",
						"Velaethaunyl",
						"Velatha",
						"Veluthil",
						"Verrona",
						"Vestele",
						"Viansola",
						"Winterflower",
						"Xanaphia",
						"Xiiltharra",
						"Yaereene",
						"Yalanilue",
						"Yathlanae",
						"Yeshelné",
						"Yghiilra",
						"Ygrainne",
						"Ynshael",
						"Yrlissa",
						"Yrneha",
						"Yrthraethra",
						"Ysmyrlda",
						"Ytharra",
						"Yulmanda",
						"Z’Beryl",
						"Zhuirentel",
						"Zoastria"
					]);
				}
				break;
			//#endregion
			//#region Firbolg
			case "firbolg":
				name = randomize([
					"Alder",
					"Almond",
					"Beech",
					"Birch",
					"Buloke",
					"Calabash",
					"Cebil",
					"Cedar",
					"Cycad",
					"Cyrilla",
					"Chestnut",
					"Dogwood",
					"Elm",
					"Eucalyptus",
					"Fir",
					"Hazel",
					"Hemlock",
					"Hickory",
					"Juniper",
					"Larch",
					"Lyonia",
					"Magnolia",
					"Mangrove",
					"Maple",
					"Meranti",
					"Nutmeg",
					"Oak",
					"Pine",
					"Palm",
					"Poplar",
					"Redwood",
					"Rosewood",
					"Sequoia",
					"Spruce",
					"Strongbark",
					"Sycamore",
					"Verawood",
					"Walnut",
					"Willow",
					"Wormwood",
					"Yew"
				]);
				break;
			//#endregion
			//#region Firenewt
			case "firenewt":
				name = randomize([
					"Sahalia (lizard)",
					"Nariyin (fiery)",
					"Harq (burn)",
					"'Ahraq (scald)",
					"Rawasib (magma)",
					"Damalon (boil)",
					"Dukhanon (smoke)",
					"Dhabulon (sear)",
					"Manalon (roast)",
					"Yaqlaa (fry)",
					"Nar (fire)",
					"Alnakhbu (toast)",
					"Lahab (flame)"
				]);
				break;
			//#endregion
			//#region Goblin
			case "goblin":
				const goblinNameParts = ["krun", "grum", "gri", "nion", "krad", "dia", "rita", "rip", "borgor", "bago", "gut", "proud", "pol", "bak"];
				name = randomize(goblinNameParts);
				name += randomize(goblinNameParts);
				name = name.charAt(0).toUpperCase() + name.slice(1);
				break;
			//#endregion
			//#region Goliath
			case "goliath":
				// goliath birth names
				name = randomize([
					"Aruk",
					"Aukan",
					"Eglath",
					"Gae-Al",
					"Gauthak",
					"Ilikan",
					"Keothi",
					"Kuori",
					"Lo-Kag",
					"Manneo",
					"Maveith",
					"Nalla",
					"Orilo",
					"Paavu",
					"Pethani",
					"Sken",
					"Thalai",
					"Thotham",
					"Uthal",
					"Vaunea",
					"Vimak"
				]);
				// nicknames
				name += " " + randomize([
					"Bearkiller",
					"Dawncaller",
					"Fearless",
					"Flintfinder",
					"Horncarver",
					"Keeneye",
					"Lonehunter",
					"Longleaper",
					"Rootsmasher",
					"Skywatcher",
					"Steadyhand",
					"Threadtwister",
					"Twice-Orphaned",
					"Twistedlimb",
					"Wordpainter"
				]);
				break;
			//#endregion
			//#region Gnome
			case "gnome":
				if (gender == "male") {
					name = randomize([
						"Alston",
						"Alvyn",
						"Boddynock",
						"Brocc",
						"Burgell",
						"Dimble",
						"Dorbo",
						"Eldon",
						"Erky",
						"Falrinn",
						"Flink",
						"Fonkin",
						"Frug",
						"Gerbo",
						"Gimble",
						"Glim",
						"Glint",
						"Gurnik",
						"Jebodah",
						"Jebeddo",
						"Kellen",
						"Mev",
						"Namfoodle",
						"Norry",
						"Orryn",
						"Roondar",
						"Seebo",
						"Sindri",
						"Skeemo",
						"Warryn",
						"Wingle",
						"Wrenn",
						"Zook"
					]);
				} else {
					name = randomize([
						"Bimpnottin",
						"Breena",
						"Caramip",
						"Carlin",
						"Donella",
						"Duvamil",
						"Ella",
						"Ellyjobell",
						"Ellywick",
						"Gellana",
						"Jamna",
						"Lilli",
						"Loopmottin",
						"Lorilla",
						"Maralie",
						"Mardnab",
						"Naithee",
						"Nissa",
						"Nomi",
						"Nyx",
						"Oda",
						"Orla",
						"Roywyn",
						"Rukhelmoth",
						"Senni",
						"Shamil",
						"Tana",
						"Villonah",
						"Waywocket",
						"Wiri",
						"Zanna",
					]);
				}
				name += " \"" + randomize([
					"Aleslosh",
					"Ashhearth",
					"Badger",
					"Cloak",
					"Diggermattock",
					"Doublelock",
					"Fiddlebender",
					"Filchbatter",
					"Flintknapper",
					"Fnipper",
					"Gardnersonson",
					"Gleamsilver",
					"Glitterstone",
					"Greatorm",
					"Hamisfore",
					"Ku",
					"Leadstopper",
					"Mirrorshade",
					"Nim",
					"Oneshoe",
					"Pathshutter",
					"Pock",
					"Sparklegem",
					"Spewgold",
					"Stumbleduck",
					"Tapfinger",
					"Thunderbonk",
					"Waywocket",
					"Weirdbottle",
				]) + "\"";
				break;
			//#endregion
			//#region Grippli
			case "grippli":
				if (gender == "male") {
					name = randomize([
						"Brillup",
						"Bullgup",
						"Chirk",
						"Dart",
						"Labllup",
						"Quartle",
						"Rublup",
						"Willup"
					]);
				} else {
					name = randomize([
						"Bellum",
						"Kaillum",
						"Que",
						"Quon",
						"Ruue",
						"Toum",
						"Wuon"
					]);
				}
				break;
			//#endregion
			//#region Grung
			case "grung":
				const grungGreenNames = [
					"Pap'k'aka",
					"Ski'di'ki'pap",
					"Ap'upu",
					"Sk'ya",
					"D'udu",
					"K'uku",
					"Dun'd'un",
					"P'oo'mp'oom",
					"Pa'n",
					"N'da",
					"B'oom",
					"Pu'dr'r'r",
					"Skiv'ipa",
					"Sk'ree'e"
				];
				const grungBlueNames = [
					"G'ot'taf'iyt",
					"F'ory'ar'iyt",
					"To'pra'tee",
					"S'abo",
					"Ta'je"
				];
				const grungPurpleNames = [
					"O'u",
					"T'r'un",
					"M'iam'",
					"Ei'ht",
					"S'yn",
					"Pla'm",
					"Tw'y",
					"Ni'on",
					"V'ae",
					"Po'r",
					"W'ae'v"
				];
				name = randomize(grungGreenNames);
				break;
			//#endregion
			//#region Halfling
			case "halfling":
				if (gender == "male") {
					name = randomize([
						"Alton",
						"Ander",
						"Atherton",
						"Bepis",
						"Bernie",
						"Bobbin",
						"Broxley",
						"Cade",
						"Callus",
						"Corrin",
						"Dannad",
						"Danniel",
						"Dellby",
						"Eddie",
						"Egart",
						"Eldon",
						"Enzo",
						"Errich",
						"Fildo",
						"Finnan",
						"Franklin",
						"Garret",
						"Garth",
						"Gilbert",
						"Gob",
						"Harol",
						"Jasper",
						"Keith",
						"Kelso",
						"Kevin",
						"Lazam",
						"Lerry",
						"Lindal",
						"Lowell",
						"Lyle",
						"Merric",
						"Mican",
						"Milo",
						"Morrin",
						"Nebin",
						"Nevil",
						"Osborn",
						"Ostran",
						"Oswalt",
						"Perrin",
						"Poppy",
						"Reed",
						"Regis",
						"Reuben",
						"Roscoe",
						"Sam",
						"Shardon",
						"Tye",
						"Ulmo",
						"Wellby",
						"Wendel",
						"Wenner",
						"Wes",
						"Wiggan"
					]);
				} else {
					name = randomize([
						"Alain",
						"Alora",
						"Andry",
						"Anne",
						"Bella",
						"Blossom",
						"Bree",
						"Brynn",
						"Cellica",
						"Callie",
						"Chenna",
						"Cora",
						"Corrin",
						"Danika",
						"Dell",
						"Eida",
						"Eran",
						"Euphemia",
						"Farrow",
						"Georgina",
						"Gynnie",
						"Harriet",
						"Havia",
						"Jasmine",
						"Jillian",
						"Jo",
						"Kithri",
						"Kyla",
						"Lavinia",
						"Lidda",
						"Locke",
						"Maegan",
						"Marigold",
						"Merla",
						"Mia",
						"Myria",
						"Nedda",
						"Nikki",
						"Nora",
						"Olivia",
						"Paela",
						"Pearl",
						"Pennie",
						"Philomena",
						"Portia",
						"Robbie",
						"Rose",
						"Rosie",
						"Samara",
						"Saral",
						"Seraphina",
						"Shaena",
						"Shandie",
						"Stacee",
						"Tawna",
						"Thea",
						"Trym",
						"Tyna",
						"Vani",
						"Verna",
						"Violet",
						"Wella",
						"Willow"
					]);
				}
				break;
			//#endregion
			//#region Hobgoblin
			case "hobgoblin":
				if (gender == "male") {
					name = randomize([
						"Aruget",
						"Biish",
						"Daavan",
						"Dagii",
						"Durnn",
						"Duulun",
						"Fenic",
						"Haruuc",
						"Hashrad",
						"Iizan",
						"Jhezon",
						"Krakuul",
						"Kurac",
						"Lhurusk",
						"Mazaan",
						"Muuka",
						"Munta",
						"Nasaar",
						"Oraan",
						"Okaat",
						"Ruus",
						"Saabak",
						"Tasaam",
						"Taak",
						"Tariic",
						"Thuun",
						"Vanii",
						"Vanon",
						"Woshar"
					]);
				} else {
					name = randomize([
						"Diitesh",
						"Ekhaas",
						"Jhazaal",
						"Khaar",
						"Kitaas",
						"Mekiis",
						"Razu",
						"Reirie",
						"Riila",
						"Senen",
						"Shaardat",
						"Tuura",
						"Ulwai"
					]);
				}
				break;
			//#endregion
			//#region Human
			case "human":
				if (gender == "male") {
					name = randomize([
						"Adam",
						"Adelard",
						"Alan",
						"Albert",
						"Aldous",
						"Aldred",
						"Alexander",
						"Alisander",
						"Anselm",
						"Arnold",
						"Arthur",
						"Bardolph",
						"Barnabas",
						"Bartholomew",
						"Basil",
						"Bennet",
						"Berenger",
						"Bernard",
						"Bertram",
						"Bryce",
						"Castor",
						"Charles",
						"Clerebold",
						"Conrad",
						"David",
						"Diggory",
						"Dinadan",
						"Drogo",
						"Edwin",
						"Eliot",
						"Elton",
						"Erol",
						"Evan",
						"Everard",
						"Frederick",
						"Geoffrey",
						"George",
						"Gerald",
						"Gilbert",
						"Giles",
						"Godfrey",
						"Gunter",
						"Guy",
						"Hamond",
						"Hardwin",
						"Henry",
						"Herbert",
						"Heward",
						"Hildebrand",
						"Hubert",
						"Hugh",
						"Jocelyn",
						"John",
						"Jonathan",
						"Kay",
						"Lance",
						"Leon",
						"Leroy",
						"Liam",
						"Lionel",
						"Lucan",
						"Manfred",
						"Mark",
						"Martin",
						"Matthew",
						"Merek",
						"Michael",
						"Miles",
						"Nicholas",
						"Nigel",
						"Niles",
						"Noah",
						"Norman",
						"Odo",
						"Paul",
						"Percival",
						"Peter",
						"Ralf",
						"Randal",
						"Raymond",
						"Reynard",
						"Richard",
						"Robin",
						"Robert",
						"Roger",
						"Roland",
						"Rolf",
						"Simon",
						"Theobald",
						"Theodoric",
						"Thomas",
						"Timm",
						"Timmothy",
						"Trevor",
						"Tristram",
						"Urian",
						"Vincent",
						"William",
						"Wolfstan",
						"Wymar"
					]);
				} else {
					name = randomize([
						"Adelaide",
						"Adelina",
						"Aelina",
						"Agatha",
						"Agnes",
						"Aldith",
						"Alice",
						"Aline",
						"Alma",
						"Althea",
						"Alyson",
						"Amelina",
						"Anais",
						"Anne",
						"Artemisia",
						"Aubrey",
						"Audry",
						"Augusta",
						"Avelina",
						"Avice",
						"Barbetta",
						"Beatrice",
						"Bertha",
						"Brangwine",
						"Bridget",
						"Brien",
						"Catelin",
						"Caterina",
						"Cecily",
						"Clare",
						"Cristina",
						"Dameta",
						"Dionisia",
						"Edeva",
						"Edith",
						"Egelina",
						"Elaine",
						"Eleanor",
						"Elizabeth",
						"Ella",
						"Elle",
						"Eloise",
						"Elysande",
						"Emeline",
						"Emeny",
						"Emma",
						"Emmeline",
						"Ermina",
						"Eva",
						"Evelune",
						"Galiena",
						"Geva",
						"Giselle",
						"Griselda",
						"Guinevere",
						"Hadwisa",
						"Helen",
						"Herleva",
						"Hugolina",
						"Ida",
						"Isabella",
						"Ivette",
						"Jacoba",
						"Jane",
						"Joan",
						"Johanna",
						"Judith",
						"Juliana",
						"Julliet",
						"Katherine",
						"Lena",
						"Margaret",
						"Margery",
						"Martha",
						"Marthurine",
						"Mary",
						"Matilda",
						"Maynild",
						"Millicent",
						"Molly",
						"Oriel",
						"Paulina",
						"Regina",
						"Ricolda",
						"Roana",
						"Robbin",
						"Rohesia",
						"Rosalind",
						"Rosamund",
						"Sarah",
						"Sela",
						"Susanna"
					]);
				}
				break;
			//#endregion
			//#region Infernal
			case "infernal":
				if (gender == "male") {
					name = randomize([
						"Abad",
						"Ahrim",
						"Akmen",
						"Akmenos",
						"Amnon",
						"Andram",
						"Astar",
						"Balam",
						"Barakas",
						"Bathin",
						"Caim",
						"Chem",
						"Cimer",
						"Cressel",
						"Damakos",
						"Ekemon",
						"Euron",
						"Fenriz",
						"Forcas",
						"Habor",
						"Iados",
						"Kairon",
						"Leucis",
						"Mamnen",
						"Mantus",
						"Marbas",
						"Melech",
						"Merihim",
						"Modean",
						"Mordai",
						"Mormo",
						"Morthos",
						"Nicor",
						"Nirgel",
						"Oriax",
						"Paymon",
						"Pelaios",
						"Purson",
						"Qemuel",
						"Raam",
						"Rimmon",
						"Sammal",
						"Skamos",
						"Tethren",
						"Thamuz",
						"Therai",
						"Valafar",
						"Vassago",
						"Xappan",
						"Zepar",
						"Zephan"
					]);
				} else {
					name = randomize([
						"Akta",
						"Anakis",
						"Armara",
						"Astaro",
						"Aym",
						"Azza",
						"Beleth",
						"Bryseis",
						"Bune",
						"Criella",
						"Damaia",
						"Decarabia",
						"Ea",
						"Gadreel",
						"Gomory",
						"Hecat",
						"Ishte",
						"Jezebeth",
						"Kali",
						"Kallista",
						"Kasdeya",
						"Lerissa",
						"Lilith",
						"Makaria",
						"Manea",
						"Markosian",
						"Mastema",
						"Naamah",
						"Nemeia",
						"Nija",
						"Orianna",
						"Osah",
						"Phelaia",
						"Prosperine",
						"Purah",
						"Pyra",
						"Rieta",
						"Ronobe",
						"Ronwe",
						"Seddit",
						"Seere",
						"Sekhmet",
						"Semyaza",
						"Shava",
						"Shax",
						"Sorath",
						"Uzza",
						"Vapula",
						"Vepar",
						"Verin"
					]);
				}
				break;
			//#endregion
			//#region Kenku
			case "kenku":
				name = randomize([
					"Basher",
					"Chukka",
					"Clanger",
					"Clonk",
					"Cutter",
					"Growler",
					"Hammerer",
					"Mouser",
					"Rat Scratch",
					"Sail Snap",
					"Slicer",
					"Smasher",
					"Whistler",
				]);
				break;
			//#endregion
			//#region Kobold
			case "kobold":
				name = randomize([
					"Arix",
					"Eks",
					"Ett",
					"Galax",
					"Garu",
					"Hagnar",
					"Hox",
					"Irtos",
					"Kashak",
					"Kovi",
					"Kubo",
					"Meepo",
					"Molo",
					"Rotom",
					"Ohsoss",
					"Sagin",
					"Sik",
					"Sniv",
					"Taklak",
					"Tes",
					"Urak",
					"Varn"
				]);
				break;
			//#endregion
			//#region Koa-Toa
			case "kuo-toa":
				name = randomize(["Too", "Mmot", "Loo", "Chog", "Laag", "Shoo", "Doo", "Gib", "Glol", "Kur", "Dag", "Gap", "Blop"]) +  randomize(["ploorg", "hagoon", "goorg", "bogg", "goop", "loorg", "daga", "gool", "goonleth"]);
				break;
			//#endregion
			//#region Lizardfolk
			case "lizardfolk":
				name = randomize([
					"Achuak (green)",
					"Aryte (war)",
					"Baeshra (animal)",
					"Darastrix (dragon)",
					"Garurt (axe)",
					"Irhtos (secret)",
					"Jhank (hammer)",
					"Kepesk (storm)",
					"Kethend (gem)",
					"Korth (danger)",
					"Kosj (small)",
					"Kothar (demon)",
					"Litrix (armor)",
					"Mirik (song)",
					"Othokent (smart)",
					"Sauriv (eye)",
					"Throden (many)",
					"Thurkear (night)",
					"Usk (iron)",
					"Valignat (burn)",
					"Vargach (battle)",
					"Verthica (mountain)",
					"Vutha (black)",
					"Vyth (steel)"
				]);
				break;
			//#endregion
			//#region Modron
			case "modron":
				const modronLetters = [
					"alpha",
					"beta",
					"gamma",
					"delta",
					"epsilon",
					"zeta",
					"eta",
					"theta",
					"iota",
					"kappa",
					"lambda",
					"mu",
					"nu",
					"xi",
					"omicron",
					"pi",
					"rho",
					"sigma",
					"tau",
					"upsilon",
					"phi",
					"chi",
					"psi",
					"omega"
				];
				name = randomize(modronLetters);
				for (let i = 0; i < 6; i++) {
					name += " " + randomize(modronLetters);
				}
				break;
			//#endregion
			//#region Northern
			case "northern":
				if (gender == "male") {
					name = randomize(["Edd", "Rob", "Ren", "Stan", "Ned"]);
					name += randomize(["ard", "is", "ert"]);
				} else {
					name = randomize(["Ar", "Cat", "San"]);
					name += randomize(["ya", "sa", "lyn"]);
				}
				break;
			//#endregion
			//#region Orc
			case "orc":
				if (gender == "male") {
					name = randomize([
						"Dench",
						"Feng",
						"Gell",
						"Henk",
						"Holg",
						"Imsh",
						"Keth",
						"Krusk",
						"Mhurren",
						"Ront",
						"Thokk",
						"Shump",
						"Argran",
						"Braak",
						"Brug",
						"Cagak",
						"Dorn",
						"Dren",
						"Druuk",
						"Gnarsh",
						"Grumbar",
						"Gubrash",
						"Hagren",
						"Hogar",
						"Karash",
						"Karg",
						"Korag",
						"Lubash",
						"Megged",
						"Mord",
						"Morg",
						"Nil",
						"Nybarg",
						"Odorr",
						"Ohr",
						"Rendar",
						"Resh",
						"Ront",
						"Rrath",
						"Sark",
						"Scrag",
						"Sheggen",
						"Tanglar",
						"Tarak",
						"Thar",
						"Trag",
						"Ugarth",
						"Varg",
						"Vilberg",
						"Yurk",
						"Zed"
					]);
				} else {
					name = randomize([
						"Arha",
						"Baggi",
						"Bendoo",
						"Bilga",
						"Brakka",
						"Creega",
						"Drenna",
						"Ekk",
						"Emen",
						"Engong",
						"Fistula",
						"Gaaki",
						"Gorga",
						"Grai",
						"Greeba",
						"Grigi",
						"Gynk",
						"Hrathy",
						"Huru",
						"Ilga",
						"Kabbarg",
						"Kansif",
						"Lagazi",
						"Lezre",
						"Murgen",
						"Murook",
						"Myev",
						"Nagrette",
						"Neeza",
						"Nella",
						"Nogu",
						"Oolah",
						"Ootah",
						"Ovak",
						"Ownka",
						"Puyet",
						"Reeza",
						"Shautha",
						"Silgre",
						"Sisyrus",
						"Sutha",
						"Tagga",
						"Tawar",
						"Tomph",
						"Ubada",
						"Vanchu",
						"Vola",
						"Volen",
						"Vorka",
						"Yevelda",
						"Zagga"
					]);
				}
				break;
			//#endregion
			//#region Ratfolk
			case "ratfolk":
				if (gender == "male") {
					name = randomize([
						"Allophrys",
						"Alticola",
						"Bakeri",
						"Baule",
						"Bolami",
						"Boylii",
						"Bufo",
						"Burti",
						"Carletoni",
						"Crinitus",
						"Forresti",
						"Gambelli",
						"Gaumeri",
						"Harbisoni",
						"Haussa",
						"Mattheyi",
						"Salvini",
						"Schmidli",
						"Spretus",
						"Stirtoni",
						"Tenellus",
					]);
				} else {
					name = randomize([
						"Albula",
						"Alpicola",
						"Arianus",
						"Attwateri",
						"Baileyi",
						"Beatae",
						"Calabyi",
						"Caroli",
						"Chevrieri",
						"Cookii",
						"Cypriacus",
						"Datae",
						"Emesi",
						"Epimelas",
						"Gracilis",
						"Keeni",
						"Merriami",
						"Musseri",
						"Neave",
						"Pahari",
						"Sorella",
					]);
				}
				break;
			//#endregion Ratfolk
			//#region Tabaxi
			case "tabaxi":
				name = randomize([
					"Afternoon Nap (Nap)",
					"Arctic Dust (Arctic)",
					"Aurora of Winter (Aurora)",
					"Bag of Nails (Nails)",
					"Bronze Peak (Bronze)",
					"Bush in the Forest (Forest)",
					"Cadence of Water (Cadence)",
					"Cool Morning (Morning)",
					"Clever Star (Star)",
					"Cloud on the Mountaintop (Cloud)",
					"Coursing River (River)",
					"Defiant Time (Defiant)",
					"Drifting Snowflake (Snowflake)",
					"Fallen Twig (Twig)",
					"Five Timber (Timber)",
					"Flask of Wine (Flask)",
					"Flickering Fire (Fire)",
					"Fresh Hide (Hide)",
					"Game of Chance (Game)",
					"Gold Wind (Wind)",
					"Hatchling Trout (Hatch)",
					"Hearty Fang (Hearty)",
					"Hidden Treasure (Treasure)",
					"Jade Shoe (Jade)",
					"Lazy Flower (Flower)",
					"Leaf on the Water (Leaf)",
					"Left-Handed Hummingbird (Bird)",
					"Merry River (River)",
					"Quiet Rain (Quiet)",
					"Rainbow After Rain (Rainbow)",
					"River Mist (River)",
					"Sapphire Clover (Sapphire)",
					"Scratch on Wood (Scratch)",
					"Seven Thundercloud (Thunder)",
					"Shadows in the Wind (Shadow)",
					"Skirt of Snakes (Snake)",
					"Sky Full of Stars (Sky)",
					"Smoking Mirror (Smoke)",
					"Snow of the Mountain (Snow)",
					"Sound of the Drum (Drum)",
					"Spring Blossom (Spring)",
					"Storm at Sea (Sea)",
					"Subtle River (Subtle)",
					"Three Earrings (Three)",
					"Tree Blossom (Blossom)",
					"True Clover (Clover)",
					"Two Dry Cloaks (Cloaks)",
					"Warm Day (Warm)",
					"Whisper on the Wind (Whisper)",
					"Winter Breath (Winter)",
				]);
				break;
			//#endregion
			//#region Tortle
			case "tortle":
				name = randomize([
					"Ambie",
					"Amble",
					"Baka",
					"Damu",
					"Gar",
					"Gura",
					"Ini",
					"Jappa",
					"Kinlek",
					"Krull",
					"Lim",
					"Lop",
					"Nortle",
					"Nulka",
					"Olo",
					"Ploqwat",
					"Quee",
					"Queg",
					"Quott",
					"Sunny",
					"Tibor",
					"Ubo",
					"Uhok",
					"Wabu",
					"Xelbuk",
					"Xopa",
					"Yog"
				]);
				break;
			//#endregion
			//#region Triton
			case "triton":
				if (gender == "male") {
					name = randomize([
						"Corus",
						"Delnis",
						"Jhimas",
						"Keros",
						"Kysh",
						"Molos",
						"Nalos",
						"Vodos",
						"Zunis"
					]);
				} else {
					name = randomize([
						"Aryn",
						"Belthyn",
						"Duthyn",
						"Feloren",
						"Otanyn",
						"Shalryn",
						"Vlaryn",
						"Wolyn"
					]);
				}
				break;
			//#endregion
			//#region Virtue
			case "virtue":
				name = randomize([
					"Ambition",
					"Art",
					"Beauty",
					"Carrion",
					"Chant",
					"Chivalry",
					"Conflict",
					"Creed",
					"Death",
					"Debauchery",
					"Despair",
					"Doom",
					"Doubt",
					"Dread",
					"Ecstasy",
					"Ennui",
					"Entropy",
					"Excellence",
					"Fear",
					"Glory",
					"Gluttony",
					"Grief",
					"Hate",
					"Hope",
					"Horror",
					"Ideal",
					"Ignominy",
					"Joy",
					"Laughter",
					"Love",
					"Lust",
					"Mayhem",
					"Misery",
					"Mockery",
					"Murder",
					"Muse",
					"Music",
					"Mystery",
					"Nowhere",
					"Open",
					"Pain",
					"Passion",
					"Poetry",
					"Power",
					"Quest",
					"Random",
					"Reverence",
					"Revulsion",
					"Secrecy",
					"Sorrow",
					"Temerity",
					"Torment",
					"Tragedy",
					"Vice",
					"Virtue",
					"War",
					"Weary",
					"Wit"
				]);
				break;
			//#endregion
			//#region Wilkoss
			case "wilkoss":
				if (gender == "male") {
					name = randomize(["Bee", "Bun", "Er", "Foz", "Gon", "Gro", "Ker"]);
					name += randomize(["ker", "son", "nie", "zie", "zo", "ver", "mit"]);
				} else {
					name = randomize(["Ab", "Cam", "Jan", "Ros", "Zo", "Prair"]);
					name += randomize(["by", "illa", "ice", "ita", "eey"]);
				}
				break;
			//#endregion
			default:
				if (gender == "male") {
					name = randomize([
						"Acko",
						"Babu",
						"Betuz",
						"Carse",
						"Dak",
						"Dengar",
						"Dexar",
						"Ejlo",
						"Enzo",
						"Farmik",
						"Grik",
						"Harpo",
						"Hurrin",
						"Imman",
						"Jyur",
						"Kwapo",
						"Larry",
						"Lirf",
						"Mako",
						"Mvu",
						"Nando",
						"Nipuum",
						"Orrin",
						"Oq",
						"Puy",
						"Preelo",
						"Quipss",
						"Renar",
						"Rimpi",
						"Seirgol",
						"Suje",
						"Tampit",
						"Trewk",
						"Ullo",
						"Vibe",
						"Vos",
						"Wlop",
						"Xyrnos",
						"Yyy",
						"Zop"
					]);
				} else {
					name = randomize([
						"Aayla",
						"Aewo",
						"Briz",
						"Beat",
						"Carf",
						"Cartu",
						"Denza",
						"Dia",
						"Ejla",
						"Eppi",
						"Firne",
						"Friju",
						"Giquop",
						"Grorn",
						"Hinok",
						"Izzy",
						"Ion'yar",
						"Jaina",
						"Jestofu",
						"Korlij",
						"Lushav",
						"Miral",
						"Nupay",
						"Oshiquo",
						"Prinyak",
						"Qralu",
						"Raura",
						"Shaak",
						"Synapti",
						"Tuzzzozox",
						"Unbrito",
						"Vaournik",
						"Viol",
						"Wyrniz",
						"Xika",
						"Yu'vu",
						"Zliwqu"
					]);
				}
				break;
		}
		return name;
	},
	last: function(species: string = "human", gender: string = "female", age: string = "adult"): string {
		var name = "";
		switch (species) {
			//#region Aarakocra
			case "aarakocra":
				name = randomize([
					"Airswimmer",
					"Breezehopper",
					"Cloudwalker",
					"Galerunner",
					"Gustfeather",
					"Skyherald",
					"Stormtalon",
					"Thunderwing",
					"Windfeather"
				]);
				break
			//#endregion Aarakocra
			//#region Anime
			case "anime":
				name = randomize([
					"Ikeda",
					"Ito",
					"Kobayashi",
					"Kondo",
					"Miyamoto",
					"Miyazaki",
					"Nakamura",
					"Saito",
					"Sakai",
					"Sato",
					"Suzuki",
					"Takahashi",
					"Takeda",
					"Tanaka",
					"Uchida",
					"Watanabe",
					"Yamamoto"
				]);
				break
			//#endregion Anime
			//#region Brokkos
			case "brokkos":
				/*
					name | role | color
					Aiutatu - helper, assists with any role that has insufficient Brokkos
					Cuocu - cook/chef
					Doto - healer
					Fermia - childcare
					Guardia - guard
					Maestru - teacher
					Produ - maker, craftsman
					Raccogli - gatherer/forager
					Scavo - digger
					Zitellu - fledgling
				*/
				if (age == "child") {
					name = "Zitellu (Fledgling)";
				}
				else
				{
					name = randomize([
						"Aiutatu (Helper)",
						"Cuocu (Cook)",
						"Doto (Healer)",
						"Fermia (Childcare)",
						"Guardia (Warrior)",
						"Maestru (Teacher)",
						"Produ (Craftsman)",
						"Raccogli (Forager)",
						"Scavo (Digger)"
					]);
				}
				break;
			//#endregion Brokkos
			//#region Dragonborn
			case "dragonborn":
				name = randomize([
					"Akambherylliax",
					"Argenthrixus",
					"Baharoosh",
					"Beryntolthropal",
					"Bhenkumbyrznaax",
					"Caavylteradyn",
					"Chumbyxirinnish",
					"Clethtinthiallor",
					"Daardendrian",
					"Delmirev",
					"Dhyrktelonis",
					"Ebynichtomonis",
					"Esstyrlynn",
					"Fharngnarthnost",
					"Ghaallixirn",
					"Grrrmmballhyst",
					"Gygazzylyshrift",
					"Hashphronyxadyn",
					"Hshhsstoroth",
					"Imbixtellrhyst",
					"Jerynomonis",
					"Jharthraxyn",
					"Kerrhylon",
					"Kimbatuul",
					"Lhamboldennish",
					"Linxakasendalor",
					"Mohradyllion",
					"Mystan",
					"Nemmonis",
					"Norixius",
					"Ophinshtalajiir",
					"Orexijandilin",
					"Pfaphnyrennish",
					"Phrahdrandon",
					"Pyraxtallinost",
					"Qyxpahrgh",
					"Raghthroknaar",
					"Shestendeliath",
					"Skaarzborroosh",
					"Sumnarghthrysh",
					"Tiammanthyllish",
					"Turnuroth",
					"Umbyrphrael",
					"Vangdondalor",
					"Verthisathurgiesh",
					"Wivvyrholdalphiax",
					"Wystongjiir",
					"Xephyrbahnor",
					"Yarjerit",
					"Zzzxaaxthroth"
				]);
				break;
			//#endregion Dragonborn
			//#region Drow
			case "drow":
				name = randomize([
					"A'Daragon",
					"Abaeir",
					"Abbylan",
					"Arabani",
					"Argith",
					"Baenre",
					"Beltaulur",
					"Blaerabban",
					"Blundyth",
					"Brevak",
					"Chaulssin",
					"Coborel",
					"Coloara",
					"Cormrael",
					"Daevion'lyr",
					"Dalael",
					"Dhalmass",
					"Dhunnyl",
					"Diliriy",
					"Dinoryn",
					"Dryaalis",
					"Duskryn",
					"Dyrr",
					"Elpragh",
					"Elpragh",
					"Faertala",
					"Filifar",
					"Gallaer",
					"Glannath",
					"Glaurach",
					"Helviiryn",
					"Hune",
					"Hunzrin",
					"Hyluan",
					"Icharyd",
					"Ilaleztice",
					"Illistyn",
					"Illykur",
					"Jhalavar",
					"Jusztiirn",
					"Keteeruae",
					"Khalazza",
					"Khalazza",
					"Kront'tane",
					"Lhalabar",
					"Lueltar",
					"Mizzrym",
					"Mlezziir",
					"Naerth",
					"Nirinath",
					"Olonrae",
					"Omriwin",
					"Philiom",
					"Quavein",
					"Rhomduil",
					"Rrostarr",
					"Rycast",
					"Seerear",
					"Ssambra",
					"T'orgh",
					"T'sarran",
					"Tanor'Thal",
					"Telenna",
					"Tlin'orzza",
					"Tlintarn",
					"Tuin",
					"Uloavae",
					"Vex",
					"Vrammyr",
					"Vrinn",
					"Waeglossz",
					"Xicton",
					"Xiltyn",
					"Yauntyrr",
					"Yauthlo",
					"Yril'Lysaen",
					"Zaphresz",
					"Zauviir",
					"Zeizerer",
					"Zolond"
				]);
			//#endregion Drow
			//#region Dwarf
			case "dwarf":
				name = randomize([
					"Aranore",
					"Balderk",
					"Battlehammer",
					"Bigtoe",
					"Bloodkith",
					"Bofdann",
					"Brawnanvil",
					"Brazzik",
					"Bronzehand",
					"Broodfist",
					"Burrowfound",
					"Caebrek",
					"Coppervein",
					"Daerdahk",
					"Dankil",
					"Daraln",
					"Deepdelver",
					"Deepforge",
					"Diamondpick",
					"Durthane",
					"Eversharp",
					"Fallack",
					"Fireforge",
					"Foamtankard",
					"Frostbeard",
					"Glanhig",
					"Goblinbane",
					"Goldfinder",
					"Gorunn",
					"Graybeard",
					"Hackinsteel",
					"Hackinstone",
					"Hammerstone",
					"Helcral",
					"Holderhek",
					"Ironfist",
					"Ironheart",
					"Kreel",
					"Loderr",
					"Lutgehr",
					"Morigak",
					"Orcfoe",
					"Rakankrak",
					"Rockseeker",
					"RubyEye",
					"Rumnaheim",
					"Silveraxe",
					"Silverstone",
					"Steelfist",
					"Steelshadow",
					"Stonespire",
					"Stormforge",
					"Stoutale",
					"Strakeln",
					"Strongbellows",
					"Strongheart",
					"Thrahak",
					"Torevir",
					"Torunn",
					"Trollbleeder",
					"Trueanvil",
					"Trueblood",
					"Ungart"
				]);
			//#endregion Dwarf
			//#region Elf
			case "elf":
				name = randomize([
					"Aelasar",
					"Aelorothi",
					"Aendryr",
					"Aerasumé",
					"Aeravansel",
					"Agayous",
					"Agrivar",
					"Ahmaquissar",
					"Alaenree",
					"Alantar",
					"Alastrarra",
					"Alavara",
					"Alenuath",
					"Alerothi",
					"Alluth",
					"Aloevan",
					"Aloro",
					"Aluianti",
					"Aluviirsaan",
					"Amakiir",
					"Amalith",
					"Amarallis",
					"Amaratharr",
					"Amarthen",
					"Amastacia",
					"Ammath",
					"Amrallatha",
					"Anuaer",
					"Argentaamn",
					"Ariessus",
					"Arnuanna",
					"Arren",
					"Ash",
					"Ashgrove",
					"Audark",
					"Auglamyr",
					"Auglathla",
					"Aunglor",
					"Autumnfire",
					"Bellas",
					"Berethryl",
					"Berevan",
					"Berilan",
					"Bharaclaiev",
					"Bhephel",
					"Blackhelm",
					"Braegen",
					"Briarbosk",
					"Brightcloak",
					"Brightsong",
					"Brightwing",
					"Caerdonel",
					"Caersaelk",
					"Calaudra",
					"Calauth",
					"Camusiil",
					"Caphaxath",
					"Casilltenirra",
					"Cathdeiryn",
					"Ceretlan",
					"Chaadren",
					"Chamaranthe",
					"Cithreth",
					"Clatharla",
					"Cormyth",
					"Coudoarluth",
					"Craulnober",
					"Crystalembers",
					"Dahast",
					"Dalanthan",
					"Dawnhorn",
					"Dhorinshyl",
					"Dlardrageth",
					"Doedance",
					"Donnathlascen",
					"Dracoseir",
					"Dree",
					"Duirsar",
					"Durothil",
					"Duskmere",
					"Duthjuth",
					"Ealoeth",
					"Eathalena",
					"Echorn",
					"Elaéyadar",
					"Elassidil",
					"Elian",
					"Ellarian",
					"Elond",
					"Eluarshee",
					"Erenaeth",
					"Ereuvyn",
					"Erkowe",
					"Erladden",
					"Erlshade",
					"Eroth",
					"Estelda",
					"Ethanasath",
					"Evanara",
					"Eveningfall",
					"Everlove",
					"Evioro",
					"Eyriendor",
					"Faerondaerl",
					"Faerondarl",
					"Falanae",
					"Fasharash",
					"Felinaun",
					"Fellmirr",
					"Fenmarel",
					"Fflannidan",
					"Firahel",
					"Floshem",
					"Floshin",
					"Fynnasla",
					"Galanodel",
					"Gildenguard",
					"Goadulphyn",
					"Goldenleaf",
					"Goltorah",
					"Gourael",
					"Greencloak",
					"Gwaelon",
					"Haell",
					"Haerlgent",
					"Haevaul",
					"Haladar",
					"Halavanthlarr",
					"Hanali",
					"Hawksong",
					"Hlarr",
					"Holimion",
					"Horineth",
					"Hyshaanth",
					"Iathrana",
					"Iazymnal",
					"Ibryiil",
					"Ilbaereth",
					"Ilbenalu",
					"Ildacer",
					"Ildroun",
					"Iliathor",
					"Iliathorr",
					"Ilnatar",
					"Ilphelkiir",
					"Immeril",
					"Ipyllasc",
					"Iranapha",
					"Irian",
					"Irithyl",
					"Ithruen",
					"Iydril",
					"Jaglene",
					"Kadelaryn",
					"Kelerandri",
					"Kelpor’ral",
					"Keove",
					"Kevanarial",
					"Koehlanna",
					"Korianthil",
					"Kraok",
					"Laelithar",
					"Laralytha",
					"Larenthanil",
					"Larethian",
					"Lathalas",
					"Laughingwater",
					"Le’Quella",
					"Leafbower",
					"Leafsigil",
					"Lharithlyn",
					"Lhoril",
					"Liadon",
					"Lightshiver",
					"Llundlar",
					"Loceath",
					"Maendellyn",
					"Maerdrym",
					"Meirityn",
					"Meliamne",
					"Mellerelel",
					"Melruth",
					"M'Haaren",
					"Miritar",
					"Mistrivvin",
					"Mistwinter",
					"Mithalvarin",
					"Moonbow",
					"Moondown",
					"Moonflower",
					"Moonglade",
					"Moonglamaer",
					"Moonshadow",
					"Moonsnow",
					"Moonweather",
					"Morningdove",
					"Mornmist",
					"Mrhulaedir",
					"Mystralath",
					"Nacnar",
					"Naelgrath",
					"Naïlo",
					"Narlbeth",
					"Neirdre",
					"Nelnueve",
					"Netyoive",
					"Never",
					"Nhachashaal",
					"Nhaéslal",
					"Nharimlur",
					"Ni’Tessine",
					"Nierde",
					"Nightmeadow",
					"Nightstar",
					"Nightwing",
					"Nihmedu",
					"Nimesin",
					"Nlossae",
					"Nolbrae",
					"Nyamtharsar",
					"Nyntynel",
					"Oakstaff",
					"Oakwood",
					"Ofandrus",
					"Olortynnal",
					"Olyrnn",
					"Omberdawn",
					"Ongluth",
					"Orama",
					"Orbryn",
					"Ortauré",
					"Ostoroth",
					"Othronus",
					"Oumryn",
					"Phenthae",
					"Pholont",
					"Presrae",
					"Q'Naepp,",
					"Qualanthri",
					"Rachiilstar",
					"Raedrimn",
					"Raethran",
					"Raryndur",
					"Reithel",
					"Revven",
					"Rhaevaern",
					"Rhothomir",
					"Rhuidhen",
					"Rhyllgallohyr",
					"Rivleam",
					"Rivvikyn",
					"Rothenel",
					"Runemaster",
					"Sarsantyr",
					"Selakiir",
					"Selevarun",
					"Selmer",
					"Selorn",
					"Shadowmantle",
					"Shadowwater",
					"Shaeremae",
					"Shaethe",
					"Shalandalan",
					"Sharrith",
					"Shaurlanglar",
					"Shraiee",
					"Shyr",
					"Siannodel",
					"Sicafei",
					"Siltral",
					"Silverbow",
					"Silverhand",
					"Silveroak",
					"Silverspear",
					"Sinaran",
					"Slenderbow",
					"Soryn",
					"Spellstalker",
					"Srinshee",
					"Starbrow",
					"Starglance",
					"Starglow",
					"Starnar",
					"Starym",
					"Stillhawk",
					"Stilmyst",
					"Straeth",
					"Strongbow",
					"Suithrasas",
					"Suldusk",
					"Sultaasar",
					"Summerstars",
					"Sunweaver",
					"Swordstar",
					"Sylvaranth",
					"Symbaern",
					"Talandren",
					"Talesspur",
					"Tamlyranth",
					"Tanagathor",
					"Tarnruth",
					"Tarsap",
					"Tarsis",
					"Tassarion",
					"Taurntyrith",
					"Teinithra",
					"Tellynnan",
					"Teshurr",
					"Thea",
					"Tiltathana",
					"Tlanbourn",
					"Tohrthaal",
					"Toralynnsyr",
					"Tornglara",
					"Torthtan",
					"Toryvhallen",
					"Trueshot",
					"Tsornyl",
					"Tyrneladhelu",
					"Uirthur",
					"Ulondarr",
					"Ulongyr",
					"Vandiir",
					"Veverell",
					"Vispasial",
					"Vyshaan",
					"Waelvor",
					"Wasanthi",
					"Whitethistle",
					"Windstar",
					"Windwalker",
					"Withrethin",
					"Xantrani",
					"Xiloscient",
					"Xistsrith",
					"Yaeldrin",
					"Yeschant",
					"Yhendorn",
					"Yraueme",
					"Yridnae",
					"Yundraer"
				]);
				break;
			//#endregion Elf
			//#region Goliath
			case "goliath":
				name = randomize([
					"Anakalathai",
					"Elanithino",
					"Gathakanathi",
					"Kalagiano",
					"Katho-Olavi",
					"Kolae-Gileana",
					"Ogolakanu",
					"Thuliaga",
					"Thunukalathi",
					"Thuunlakalaga",
					"Vaimei-Laga",
				]);
				break;
			//#endregion Goliath
			//#region Gnome
			case "gnome":
				name = randomize([
					"Beren",
					"Daergel",
					"Fleagol",
					"Folkor",
					"Garrick",
					"Glinckle",
					"Nackle",
					"Murnig",
					"Ningel",
					"Raulnor",
					"Scheppen",
					"Timbers",
					"Turen",
					"Uvarkk",
				]);
				break;
			//#endregion Gnome
			//#region Halfling
			case "halfling":
				name = randomize([
					"Appleblossom",
					"Bigheart",
					"Brightmoon",
					"Brushgather",
					"Cherrycheeks",
					"Cherryport",
					"Copperkettle",
					"Deephollow",
					"Elderberry",
					"Fairkettle",
					"Fastfoot",
					"Fatrabbit",
					"Fiddlewick",
					"Glenfellow",
					"Goldfound",
					"Goodbarrel",
					"Goodearth",
					"Greenbottle",
					"Greenleaf",
					"Highhill",
					"Hilltopple",
					"Hogcollar",
					"Honeypot",
					"Honeymaker",
					"Jamjar",
					"Kettlewhistle",
					"Leagallow",
					"Littlefoot",
					"Moxie",
					"Nimblefingers",
					"Porridgepot",
					"Quickknife",
					"Quickstep",
					"Reedfellow",
					"Satinleaf",
					"Shadowquick",
					"Silvereyes",
					"Smoothhands",
					"Stonebridge",
					"Stoutman",
					"Strongbones",
					"Sunmeadow",
					"Swiftwhistle",
					"Tallfellow",
					"Tealeaf",
					"Tenpenny",
					"Thistletop",
					"Thorngage",
					"Tosscobble",
					"Underbough",
					"Underfoot",
					"Warmwater",
					"Whispermouse",
					"Wildcloak",
					"Wildheart",
					"Wiseacre"
				]);
				break;
			//#endregion Halfling
			//#region Hobgoblin
			case "hobgoblin":
				name = randomize([
					"Baaz",
					"Draet",
					"Draguus",
					"Gan’duur",
					"Gantii Vus",
					"Ghaal Sehn",
					"Kuun",
					"Mbar’ost",
					"Mur Talaan",
					"Nasaar",
					"Rhukaan Taash",
					"Shaart",
					"Stormcaller",
					"Thaar",
					"Uhl",
					"Volaar"
				]);
				break;
			//#endregion Hobgoblin
			//#region Human
			case "human":
				name = randomize([
					"Archer",
					"Baker",
					"Becket",
					"Blackwood",
					"Brewer",
					"Butcher",
					"Carpenter",
					"Carter",
					"Carver",
					"Clark",
					"Cobbler",
					"Cooper",
					"Cook",
					"Crowe",
					"Dyer",
					"Everly",
					"Faire",
					"Farmer",
					"Faulkner",
					"Fisher",
					"Fletcher",
					"Flynn",
					"Freeman",
					"Fuller",
					"Gardener",
					"Glover",
					"Hunt",
					"Jenkins",
					"Judge",
					"Knight",
					"Law",
					"Mason",
					"Miller",
					"Miner",
					"Page",
					"Parker",
					"Payne",
					"Potter",
					"Rolfe",
					"Sawyer",
					"Slater",
					"Smith",
					"Taylor",
					"Thatcher",
					"Turner",
					"Ward",
					"Weaver",
					"Wood",
					"Wright"
				]);
				break;
			//#endregion Human
			//#region Ratfolk
			case "ratfolk":
				name = randomize([
					"Arrogans",
					"Blangorum",
					"Devia",
					"Elator",
					"Enganus",
					"Exulans",
					"Galensis",
					"Ingens",
					"Koopmani",
					"Lepida",
					"Leucopus",
					"Losea",
					"Lugens",
					"Mordax",
					"Niobe",
					"Norvegicus",
					"Ordii",
					"Osgoodi",
					"Palatina",
					"Palmarum",
					"Pococki",
					"Rattus",
					"Sanila",
					"Satarae",
					"Steini",
					"Tanezumi",
				]);
				break;
			//#endregion Ratfolk
			//#region Tabaxi
			case "tabaxi":
				name = randomize([
					"Bright Cliffs",
					"Distant Rain",
					"Mountain Tree",
					"Rumbling River",
					"Snoring Mountain"
				]);
				break;
			//#endregion Tabaxi
			//#region Triton
			case "triton":
				name = randomize([
					"Bazath",
					"Dnoth",
					"Jastogoth",
					"Mestoth",
					"Modrith",
					"Mokroth",
					"Morjath",
					"Morskath",
					"Morskoth",
					"Podith",
					"Paroxath",
					"Rakath",
					"Toplath",
					"Tyverith",
					"Valovith",
				]);
				break;
			//#endregion Triton
			default:
				break;
		}
		return name;
	},
	full: function(species: string = "human", gender: string = "female", age: string = "adult"): string {
		let n = NameGenerator;
		switch (species) {
			case "aarakocra":
				// roughly 1 in 4 aarakocra should have a last name to aid in communications with other species.
				if (Math.round(Math.random() * 3) == 3) {
					return n.first("aarakocra", gender, age) + " " + n.last("aarakocra", gender, age);
				} else {
					return n.first("aarakocra", gender, age);
				}
			case "aasimar":
				return n.first("human", gender, age) + " " + n.last("human", gender, age);
			case "brokkos":
			case "dragonborn":
			case "drow":
			case "dwarf":
			case "elf":
				return n.first(species, gender, age) + " " + n.last(species, gender, age);
			case "genasi":
				return n.first("human", gender, age) + " " + n.last("human", gender, age);
			case "goliath":
			case "gnome":
			case "halfling":
				return n.first(species, gender, age) + " " + n.last(species, gender, age);
			case "halfelf":
				return (n.first("elf", gender, age) + " " + n.last("human", gender, age));
			case "halforc":
				return (n.first("orc", gender, age) + " " + n.last("human", gender, age));
			case "hobgoblin":
			case "human":
				return n.first(species, gender, age) + " " + n.last(species, gender, age);
			case "kitsune":
				return n.first("anime", gender, age) + " " + n.last("anime", gender, age);
			case "kuotoa":
			case "kuo-toa":
				return n.first("kuo-toa", gender, age);
			case "ratfolk":
				return n.first(species, gender, age) + " " + n.last(species, gender, age);
			case "tabaxi":
				// return n.first("tabaxi", gender, age) + " " + n.last("tabaxi", gender, age);
				return n.first("tabaxi", gender, age);
			case "triton":
				return n.first(species, gender, age) + " " + n.last(species, gender, age);
			case "tiefling":
				if (Math.round(Math.random()) == 0) {
					return n.first("virtue", gender, age);
				} else {
					return n.first("infernal", gender, age);
				}
			default:
				return n.first(species, gender, age);
		}
	}
}